server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_label_logging]
        action: keep
        regex: enabled

      - source_labels: [__meta_docker_container_label_app]
        target_label: app
      - source_labels: [__meta_docker_container_label_job]
        target_label: job
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: container
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream

    pipeline_stages:
      - match:
          selector: '{app="api"}'
          stages:
            - json:
                expressions:
                  time: time
                  level: level
                  message: message
                  service: service
                  method: method
                  path: path
                  status: status
                  latency_ms: latency_ms
                  trace_id: trace_id
                  span_id: span_id
            - timestamp:
                source: time
                format: UnixMs
            - labels:
                service:
                method:
                path:
                status:
                level:
            - output:
                source: message

      - match:
          selector: '{app="worker"}'
          stages:
            - json:
                expressions:
                  asctime: asctime
                  level: level
                  msg: message
                  queue: props.queue
                  result: props.result
                  trace_id: props.trace_id
                  span_id: props.span_id
            - timestamp:
                source: asctime
                format: RFC3339
            - labels:
                level:
                queue:
                result:
            - output:
                source: msg
