services:
  # Log Aggregation
  loki:
    image: grafana/loki
    command: ["-config.file=/etc/loki/local-config.yml"]
    volumes:
      - ./loki/config:/etc/loki
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks: [obsnet]

  promtail:
    image: grafana/promtail
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ./promtail:/etc/promtail
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "9080:9080"
    networks: [obsnet]
    depends_on: [loki]

  # Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks: [obsnet]

  # Metrics
  prometheus:
    image: prom/prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.retention.time=7d"]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [obsnet]

  # RabbitMQ Exporter
  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    environment:
      RABBIT_URL: http://rabbitmq:15672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    ports: ["9419:9419"]
    networks: [obsnet]

  # Dashboarding
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    networks: [obsnet]
    depends_on: [loki]

networks:
  obsnet:
    name: obsnet

volumes:
  loki-data: